// Fill out your copyright notice in the Description page of Project Settings.


#include "FinalMysterySolvingRoomClass.h"
#include "Particles/ParticleSystemComponent.h"  // ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ãƒ‘ãƒ¼ãƒ†ã‚£ã‚¯ãƒ«ã®ã‚¤ãƒ³ã‚¯ãƒ«ãƒ¼ãƒ‰
#include "NiagaraComponent.h"
#include "NiagaraFunctionLibrary.h"           // ã‚¨ãƒ•ã‚§ã‚¯ãƒˆã‚’ã‚¹ãƒãƒ¼ãƒ³ã—ãŸã‚Šã—ãŸã„æ™‚ã«å¿…è¦
#include "Components/PointLightComponent.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "GameFramework/Actor.h"
#include "Components/StaticMeshComponent.h"
#include "DoorMover.h"
#include "Grabber.h"

// Sets default values for this component's properties
UFinalMysterySolvingRoomClass::UFinalMysterySolvingRoomClass()
{
	// Set this component to be initialized when the game starts, and to be ticked every frame.  You can turn these features
	// off to improve performance if you don't need them.
	PrimaryComponentTick.bCanEverTick = true;
}


// Called when the game starts
void UFinalMysterySolvingRoomClass::BeginPlay()
{
	Super::BeginPlay();
    bLightingManualOn = true;
	World = GetWorld();
	if (!World)
    {
        UE_LOG(LogTemp, Error, TEXT("UTriggerComponent: GetWorld() returned nullptr!"));
    }
}


// Called every frame
void UFinalMysterySolvingRoomClass::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
    UDoorMover* doorMoverComponent = doorActor->FindComponentByClass<UDoorMover>();
    doorMoverComponent->StorneDoorMoverFunction(DeltaTime);
	deltaTime = DeltaTime;
    StateOfTheCandle();
	OverlapJudgmentFunction(); //ã‚ªãƒ¼ãƒãƒ¼ãƒ©ãƒƒãƒ—ã—ã¦ã‚‹ã‹
	DoYouHaveBronzeStatueOrPlaced(); //éŠ…åƒã‚’æŒã£ã¦ã‚‹ã‹ã¾ãŸã¯ç½®ã‹ã‚Œã¦ã„ã‚‹ã‹
	CandleDoYouHaveFunction(); //Candleã‚’æŒã£ã¦ã‚‹ã‹
}
//éŠ…åƒæŒã£ã¦ãŸå ´åˆãƒŠãƒ“ã‚²ãƒ¼ã‚¿ãƒ¼(ãƒ­ã‚¦ã‚½ã‚¯ã®ç«)ã‚’æ¶ˆã™
void UFinalMysterySolvingRoomClass::CandlEeraseFunction(bool isCandleVisibility)
{
	for (AActor* child : candleActors)
    {
        if (!child) continue;

        UE_LOG(LogTemp, Warning, TEXT("child Comp: %s"), *child->GetName());
        // ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ãƒ‘ãƒ¼ãƒ†ã‚£ã‚¯ãƒ«ã®å‡¦ç†
        if (child->GetName().Contains("Candle"))
        {
            if (UNiagaraComponent* niagaraComp = child->FindComponentByClass<UNiagaraComponent>())
            {
                UE_LOG(LogTemp, Warning, TEXT("Niagara Comp: %s"), *niagaraComp->GetName());

                // ãƒ‘ãƒ¼ãƒ†ã‚£ã‚¯ãƒ«ã‚’åˆ¶å¾¡
                if (isCandleVisibility)
                {
                    niagaraComp->SetVisibility(true);  // æç”»ã‚’å†é–‹
                    UE_LOG(LogTemp, Display, TEXT("ğŸ”¥ Niagara Activated and Visible"));
                }
                else
                {
                    niagaraComp->SetVisibility(false);  // æç”»ã‚’éè¡¨ç¤º
                    UE_LOG(LogTemp, Display, TEXT("ğŸ§¯ Niagara Deactivated and Hidden"));
                }
            }
        }
        // ãƒã‚¤ãƒ³ãƒˆãƒ©ã‚¤ãƒˆã®å‡¦ç†
        for(AActor* pointLightActor : pointLightActors)
        {
            if (pointLightActor->GetName().Contains("PointLight"))
            {
                if (UPointLightComponent* lightComp = pointLightActor->FindComponentByClass<UPointLightComponent>())
                {
                    lightComp->SetVisibility(isCandleVisibility);
                }
            }
        }        
    }
}
//ã‚­ãƒ£ãƒ³ãƒ‰ãƒ«ãŒç‚¹ã„ã¦ã„ã‚‹ã‹
void UFinalMysterySolvingRoomClass::StateOfTheCandle()
{
    bool bAllHidden = true, bAllVisible = true;
    
	for (AActor* child : candleActors)
    {
        if (!child) continue;

        bool bParticleVisible = false;
        bool bLightVisible = false;
        UE_LOG(LogTemp, Warning, TEXT("child Comp: %s"), *child->GetName());
        // ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ãƒ‘ãƒ¼ãƒ†ã‚£ã‚¯ãƒ«ã®å‡¦ç†
        if (child->GetName().Contains("Candle"))
        {
            if (UNiagaraComponent* niagaraComp = child->FindComponentByClass<UNiagaraComponent>())
            {
                bParticleVisible = niagaraComp->IsVisible();
            }
        }

        // ãƒã‚¤ãƒ³ãƒˆãƒ©ã‚¤ãƒˆã®å‡¦ç†
        for(AActor* pointLightActor : pointLightActors)
        {
            if (pointLightActor->GetName().Contains("PointLight"))
            {
                if (UPointLightComponent* lightComp = pointLightActor->FindComponentByClass<UPointLightComponent>())
                {
                    bLightVisible = lightComp->IsVisible();
                }
            }
        }

        // **ç‚ã¨å…‰ãŒä¸¡æ–¹ã¤ã„ã¦ã„ãŸã‚‰ trueã€ã©ã¡ã‚‰ã‹ã§ã‚‚æ¶ˆãˆã¦ã„ãŸã‚‰ false**
        bool bCandleVisible = bParticleVisible && bLightVisible;
        bAllHidden &= !bCandleVisible;  // 1ã¤ã§ã‚‚ã¤ã„ã¦ã„ãŸã‚‰ bAllHidden = false
        bAllVisible &= bCandleVisible;  // 1ã¤ã§ã‚‚æ¶ˆãˆã¦ã„ãŸã‚‰ bAllVisible = false
        UE_LOG(LogTemp, Warning, TEXT("ğŸ”¥ Particle Visible: %s"), bParticleVisible ? TEXT("true") : TEXT("false"));
        UE_LOG(LogTemp, Warning, TEXT("ğŸ’¡ Light Visible: %s"), bLightVisible ? TEXT("true") : TEXT("false"));
        UE_LOG(LogTemp, Warning, TEXT("ğŸ•¯ï¸ bCandleVisible: %s"), bCandleVisible ? TEXT("true") : TEXT("false"));
        UE_LOG(LogTemp, Warning, TEXT("ğŸ”’ isCandleGrabbed: %s"), isCandleGrabbed ? TEXT("true") : TEXT("false"));
        
    }
    //ã™ã¹ã¦æ¶ˆãˆã¦ã„ãŸã‚‰ isCandleGrabbed = trueã€ã™ã¹ã¦ã¤ã„ã¦ã„ãŸã‚‰ isCandleGrabbed = false ã«ãª
    isCandleGrabbed = bAllHidden ? true : bAllVisible ? false : isCandleGrabbed;
    UE_LOG(LogTemp, Display, TEXT("ğŸ”¥ isCandleGrabbed: %s"), isCandleGrabbed ? TEXT("true") : TEXT("false"));

}
//ãƒ‰ã‚¢ã‚’å‹•ã‹ã›ã‚‹ã‹
void UFinalMysterySolvingRoomClass::DoorMoveJudgeFunction(bool isDoorMover)
{
	if (!doorActor) 
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ Not doorActor !"));
		return;
	}

    UDoorMover* doorMoverComponent = doorActor->FindComponentByClass<UDoorMover>();
    
    if(!doorMoverComponent){ UE_LOG(LogTemp, Warning, TEXT("âŒNot doorMoverCOmponent !")); return;}
    doorMoverComponent->SetShouldMove(isDoorMover);
    //doorMoverComponent->StorneDoorMoverFunction(deltaTime);
}

//éŠ…åƒã‚’æŒã£ã¦ã‚‹ã‹ã¾ãŸã¯ç½®ã‹ã‚Œã¦ã„ã‚‹ã‹
void UFinalMysterySolvingRoomClass::DoYouHaveBronzeStatueOrPlaced()
{
    AActor* playerActor = FindActorByName(GetWorld(), TEXT("BP_Player")); //Worldã«BP_PlayerãŒå­˜åœ¨ã—ãŸã‚‰playerActorã«ä»£å…¥
	UGrabber* grabberComponent = playerActor->FindComponentByClass<UGrabber>();
	if(!grabberComponent)
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒNot grabberComponent!"));
		return;	
	}

    if(grabberComponent->isBronzeStatueGrabbed == true)
    {
        //æ‰‹å‹•ã§ç‚¹ç¯å¯èƒ½ã«ã•ã›ã‚‹
        if(bLightingManualOn)
        {
            CandlEeraseFunction(false);
            DoorMoveJudgeFunction(false); //ã™ã¹ã¦æ¶ˆãˆã¦ã„ãŸã‚‰ã€ãƒ‰ã‚¢ãŒé–‰ã¾ã‚‹
            bLightingManualOn = false;
        }
    }
    else
    {
        // ã‚ªãƒ¼ãƒãƒ¼ãƒ©ãƒƒãƒ—ä¸­ã®ã™ã¹ã¦ã®ã‚¢ã‚¯ã‚¿ãƒ¼ã‚’å–å¾—
        TArray<AActor*> overlappingActors;
        GetOverlappingActors(overlappingActors);
        // éŠ…åƒã‚¢ã‚¯ã‚¿ãƒ¼ãŒã‚ªãƒ¼ãƒãƒ¼ãƒ©ãƒƒãƒ—ã—ã¦ã„ã‚‹ã‹ç¢ºèª
        for (AActor* actor : overlappingActors)
        {
            UE_LOG(LogTemp, Warning, TEXT("actor: %s"),*actor->GetName());
            if(!bronzeStatueActor)
            {
                UE_LOG(LogTemp, Warning, TEXT("Not BronzeStatueActor!"));
                return;
            }
            if(bronzeStatueActor)
            {
                if (IsOverlappingActor(actor))
                {
                    DoorMoveJudgeFunction(true); //ã™ã¹ã¦ã¤ã„ã¦ã„ãŸã‚‰ã€ãƒ‰ã‚¢ãŒé–‹ã
                    CandlEeraseFunction(true);
                    bLightingManualOn = true; //æ‰‹å‹•ã§ç‚¹ç¯ã§ããªã„ã‚ˆã†ã«ã™ã‚‹
                    UE_LOG(LogTemp, Display, TEXT("Overlapping with Bronze Statue!"));
                }
            }
        }
        //CandlEeraseFunction(true);
        UE_LOG(LogTemp, Warning, TEXT("âŒNot éŠ…åƒ Grabbed!"));
    }
    if(isCandleGrabbed) //ã™ã¹ã¦æ¶ˆãˆã¦ã„ãŸã‚‰ isCandleGrabbed = true
    {
        DoorMoveJudgeFunction(false); //ã™ã¹ã¦ã¤ã„ã¦ã„ãŸã‚‰ã€ãƒ‰ã‚¢ãŒé–‰ã˜ã‚‹
        if(bIsCandleGrabbedMessageOnlyOnce)
        {
            if(grabberComponent)
                grabberComponent->bIsCandleGrabbedMessage = true; //ã‚­ãƒ£ãƒ³ãƒ‰ãƒ«æŒã¦ã‚‹ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸è¡¨ç¤º
            bIsCandleGrabbedMessageOnlyOnce = false; //æŒã¦ã‚‹ã‹ã‚­ãƒ£ãƒ³ãƒ‰ãƒ«ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã®boolåˆ¤å®šã‚’é©ç”¨ã‚’ä¸€å›ã®ã¿ã«ã™ã‚‹ãŸã‚ã®åˆ¤å®š
        }
    }
    else //ã™ã¹ã¦ã¤ã„ã¦ã„ãŸã‚‰ isCandleGrabbed = false
    {
        DoorMoveJudgeFunction(true); //ã™ã¹ã¦ã¤ã„ã¦ã„ãŸã‚‰ã€ãƒ‰ã‚¢ãŒé–‹ã
        if(!bIsCandleGrabbedMessageOnlyOnce)
        {
            if(grabberComponent)
                grabberComponent->bIsCandleGrabbedMessage = false; //ã‚­ãƒ£ãƒ³ãƒ‰ãƒ«æŒã¦ã‚‹ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸éè¡¨ç¤º
            bIsCandleGrabbedMessageOnlyOnce = true; //æŒã¦ã‚‹ã‹ã‚­ãƒ£ãƒ³ãƒ‰ãƒ«ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã®boolåˆ¤å®šã‚’é©ç”¨ã‚’ä¸€å›ã®ã¿ã«ã™ã‚‹ãŸã‚ã®åˆ¤å®š
        }
    }
}

// æŒ‡å®šã—ãŸåå‰ã®ã‚¢ã‚¯ã‚¿ãƒ¼ã‚’ãƒ¯ãƒ¼ãƒ«ãƒ‰å†…ã§æ¤œç´¢ã™ã‚‹é–¢æ•°
AActor* UFinalMysterySolvingRoomClass::FindActorByName(UWorld* world, const FString& actorName)
{
    if (world)  // ãƒ¯ãƒ¼ãƒ«ãƒ‰ãŒæœ‰åŠ¹ã‹ã©ã†ã‹ã‚’ç¢ºèª
    {
        // TActorIteratorã‚’ä½¿ã£ã¦ã€ãƒ¯ãƒ¼ãƒ«ãƒ‰å†…ã®ã™ã¹ã¦ã®ã‚¢ã‚¯ã‚¿ãƒ¼ã‚’ã‚¤ãƒ†ãƒ¬ãƒ¼ãƒˆã™ã‚‹
        for (TActorIterator<AActor> actorIterator(world); actorIterator; ++actorIterator)
        {
            // ç¾åœ¨ã®ã‚¢ã‚¯ã‚¿ãƒ¼ã®åå‰ãŒä¸€è‡´ã™ã‚‹ã‹ã©ã†ã‹ã‚’ç¢ºèª
            if (actorIterator->GetName().Contains(actorName))
            {
                return *actorIterator;  // ä¸€è‡´ã™ã‚‹ã‚¢ã‚¯ã‚¿ãƒ¼ã‚’è¦‹ã¤ã‘ãŸå ´åˆã€ã‚¢ã‚¯ã‚¿ãƒ¼ã‚’è¿”ã™
            }
        }
    }
    return nullptr;  // ä¸€è‡´ã™ã‚‹ã‚¢ã‚¯ã‚¿ãƒ¼ãŒè¦‹ã¤ã‹ã‚‰ãªã‘ã‚Œã°nullptrã‚’è¿”ã™
}

//ã‚ªãƒ¼ãƒãƒ¼ãƒ©ãƒƒãƒ—ä¸­ã®ã‚¢ã‚¯ã‚¿ãƒ¼ã‚’å–å¾—ã™ã‚‹é–¢æ•°
AActor* UFinalMysterySolvingRoomClass::GetAcceptableActor()
{
    TArray<AActor*> actors; //ã‚ªãƒ¼ãƒãƒ¼ãƒ©ãƒƒãƒ—ã—ã¦ã„ã‚‹ã‚¢ã‚¯ã‚¿ãƒ¼å–å¾—ã®ãŸã‚ã®é…åˆ—
    GetOverlappingActors(actors); //ã‚ªãƒ¼ãƒãƒ¼ãƒ©ãƒƒãƒ—ã—ãŸã‚¢ã‚¯ã‚¿ãƒ¼ã‚’å–å¾—
    for(AActor* actor : actors)  //ã‚¢ã‚¯ã‚¿ãƒ¼ã”ã¨ã«ãƒ«ãƒ¼ãƒ—å‡¦ç†
    {
        bool hasAcceptableTag = actor->ActorHasTag(acceptableActorTag); //è¨±å®¹ã‚¿ã‚°ã‚’æŒã£ã¦ã„ã‚‹ã‹åˆ¤å®š(éŠ…åƒ)
        bool isGrabbed = actor->ActorHasTag("Grabbed"); //æ´ã¾ã‚Œã¦ã„ã‚‹ã‹åˆ¤å®š
        if(hasAcceptableTag && !isGrabbed) //è¨±å®¹ã‚¿ã‚°ãŒã‚ã‚Šã€æ´ã¾ã‚Œã¦ã„ãªã„å ´åˆ
        {
            return actor; //è©²å½“ã‚¢ã‚¯ã‚¿ãƒ¼ã‚’è¿”ã™
        }
    }
    return nullptr; //è©²å½“ã‚¢ã‚¯ã‚¿ãƒ¼ãŒãªã„å ´åˆã¯nullptrã‚’è¿”ã™
}

//Candleã‚’æŒã£ã¦ã‚‹ã‹
void UFinalMysterySolvingRoomClass::CandleDoYouHaveFunction() 
{
    ECollisionChannel grabberChannel = ECC_GameTraceChannel2;
    UStaticMeshComponent* meshComponent = grabbedCandleActor->FindComponentByClass<UStaticMeshComponent>();
    meshComponent->SetCollisionResponseToChannel(grabberChannel,isCandleGrabbed ? ECR_Block : ECR_Ignore);
}
//ã‚ªãƒ¼ãƒãƒ¼ãƒ©ãƒƒãƒ—ã—ã¦ã‚‹ã‹
void UFinalMysterySolvingRoomClass::OverlapJudgmentFunction()
{
	AActor* playerActor = FindActorByName(GetWorld(), TEXT("BP_Player")); //Worldã«BP_PlayerãŒå­˜åœ¨ã—ãŸã‚‰playerActorã«ä»£å…¥
	if(!playerActor) UE_LOG(LogTemp, Warning, TEXT("âŒã€€Not playerActor!")) return;

    UGrabber* grabberComponent = playerActor->FindComponentByClass<UGrabber>();

    if(IsOverlappingActor(grabbedCandleActor))
    {
        if(!grabberComponent) UE_LOG(LogTemp, Warning, TEXT("âŒNot grabberComponent!")) return;
        grabberComponent->SetGargoyleAndStandMessageDisplayJudge(false,true);
    }
}