// Fill out your copyright notice in the Description page of Project Settings.


#include "GameMode_Pause.h"
#include "Kismet/GameplayStatics.h" // ã‚·ãƒ¼ãƒ³é·ç§»ã‚„ãƒ¦ãƒ¼ãƒ†ã‚£ãƒªãƒ†ã‚£é–¢æ•°ã‚’ä½¿ã†ãŸã‚
#include "GameFramework/PlayerController.h" // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼æ“ä½œã‚„å…¥åŠ›åˆ‡ã‚Šæ›¿ãˆãªã©ã«ä½¿ç”¨
#include "GameFramework/Character.h" // ACharacterã‚’ä½¿ã†ãŸã‚ã®ãƒ˜ãƒƒãƒ€ãƒ¼
#include "GameFramework/CharacterMovementComponent.h" // UCharacterMovementComponentã‚’ä½¿ã†ãŸã‚ã®ãƒ˜ãƒƒãƒ€ãƒ¼
#include "Components/TextBlock.h" //UTextBlockã‚¯ãƒ©ã‚¹ä½¿ã†ãŸã‚ã®ãƒ˜ãƒƒãƒ€ãƒ¼
#include "Internationalization/Text.h" //FTextã‚¯ãƒ©ã‚¹ã‚’ä½¿ã†ãŸã‚ã®ãƒ˜ãƒƒãƒ€ãƒ¼

// Sets default values for this component's properties

AGameMode_Pause::AGameMode_Pause()
{
    PrimaryActorTick.bCanEverTick = false; // æ¯ãƒ•ãƒ¬ãƒ¼ãƒ æ›´æ–°ã¯ä¸è¦
    AutoReceiveInput = EAutoReceiveInput::Player0;
}

void AGameMode_Pause::BeginPlay()
{
    Super::BeginPlay();
    APlayerController* PC = UGameplayStatics::GetPlayerController(GetWorld(), 0);
    if (!PC) return;

    EnableInput(PC);

    // ã‚¿ãƒ–ã‚­ãƒ¼ã‚’ç›´æ¥ãƒã‚¤ãƒ³ãƒ‰ï¼ˆãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆè¨­å®šä¸è¦ï¼‰
    if (!InputComponent)
    {
        InputComponent = NewObject<UInputComponent>(this, TEXT("PauseInputComponent"));
        InputComponent->RegisterComponent();
        AddInstanceComponent(InputComponent);
    }
    FInputActionBinding& TabBind = InputComponent->BindAction("PauseButton", IE_Pressed, this, &AGameMode_Pause::Pause);
    TabBind.bExecuteWhenPaused = true; // ğŸ”¥ ãƒãƒ¼ã‚ºä¸­ã‚‚æœ‰åŠ¹

    APlayerController* playerController = UGameplayStatics::GetPlayerController(this, 0); // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©å–å¾—
    if (playerController)
    {
        playerController->EnableInput(playerController); // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©ã®å…¥åŠ›ã‚’å†æœ‰åŠ¹åŒ–

        APawn* playerPawn = playerController->GetPawn(); // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®Pawnã‚’å–å¾—
        if (playerPawn)
        {
            playerPawn->EnableInput(playerController); // Pawnå´ã§ã‚‚å…¥åŠ›ã‚’å†æœ‰åŠ¹åŒ–ï¼ˆå¿µã®ãŸã‚ï¼‰

            ACharacter* character = Cast<ACharacter>(playerPawn); // ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã«ã‚­ãƒ£ã‚¹ãƒˆ
            if (character && character->GetCharacterMovement()) // CharacterMovementãŒã‚ã‚‹ã‹ç¢ºèª
            {
                // ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ç§»å‹•ãƒ¢ãƒ¼ãƒ‰ã‚’ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã«æˆ»ã™
                character->GetCharacterMovement()->SetMovementMode(EMovementMode::MOVE_Walking); // æ­©è¡ŒçŠ¶æ…‹ã«æˆ»ã™
            }
        }
        // å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã«æˆ»ã™
        FInputModeGameOnly inputMode; // ã‚²ãƒ¼ãƒ å°‚ç”¨ã®å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’ä½œæˆ
        playerController->SetInputMode(inputMode); // å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’ã‚²ãƒ¼ãƒ å°‚ç”¨ã«åˆ‡ã‚Šæ›¿ãˆã‚‹
        playerController->bShowMouseCursor = false; // ãƒã‚¦ã‚¹ã‚«ãƒ¼ã‚½ãƒ«ã‚’éè¡¨ç¤º
    }
}


void AGameMode_Pause::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
}

void AGameMode_Pause::Pause()
{
    if (!bIsPaused) // ãƒãƒ¼ã‚ºä¸­ã§ãªã‘ã‚Œã°
    {
        UGameplayStatics::SetGamePaused(GetWorld(), true); // âœ… ãƒãƒ¼ã‚ºçŠ¶æ…‹ã«ã™ã‚‹
        ShowPauseMenu();   // UIã‚’è¡¨ç¤º
        bIsPaused = true;  // ãƒãƒ¼ã‚ºçŠ¶æ…‹ã«å¤‰æ›´
    }
    else // ãƒãƒ¼ã‚ºä¸­ãªã‚‰
    {
        UGameplayStatics::SetGamePaused(GetWorld(), false); // âœ… ãƒãƒ¼ã‚ºè§£é™¤
        HidePauseMenu();   // UIã‚’éè¡¨ç¤º
        bIsPaused = false; // ãƒãƒ¼ã‚ºè§£é™¤çŠ¶æ…‹ã«å¤‰æ›´
    }
}

void AGameMode_Pause::ShowPauseMenu()
{
    APlayerController* PlayerController = UGameplayStatics::GetPlayerController(this, 0);
    if (!pauseWidgetClass || !PlayerController) return;

    if (!pauseOverWidget)
    {
        pauseOverWidget = CreateWidget<UUserWidget>(PlayerController, pauseWidgetClass);
    }

    if (pauseOverWidget && !pauseOverWidget->IsInViewport())
    {
        pauseOverWidget->AddToViewport();

        // ğŸ’¡ ã“ã“ã‚’ä¿®æ­£ï¼ï¼
        FInputModeGameAndUI inputMode; // ã‚²ãƒ¼ãƒ ï¼‹UI ä¸¡æ–¹æœ‰åŠ¹ã«ã™ã‚‹
        inputMode.SetWidgetToFocus(pauseOverWidget->TakeWidget());
        inputMode.SetLockMouseToViewportBehavior(EMouseLockMode::DoNotLock);

        PlayerController->SetInputMode(inputMode);    // å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’åˆ‡ã‚Šæ›¿ãˆã‚‹
        PlayerController->bShowMouseCursor = true;    // ã‚«ãƒ¼ã‚½ãƒ«è¡¨ç¤º
    }
}

void AGameMode_Pause::HidePauseMenu()
{
    APlayerController* PlayerController = UGameplayStatics::GetPlayerController(this, 0); // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©å–å¾—
    if (!PlayerController || !pauseOverWidget) return; // å–å¾—å¤±æ•—ã‚„UIæœªä½œæˆãªã‚‰ä¸­æ–­

    pauseOverWidget->RemoveFromParent(); // UIã‚’éè¡¨ç¤ºã«ã™ã‚‹ï¼ˆViewportã‹ã‚‰å‰Šé™¤ï¼‰

    FInputModeGameOnly inputMode; // ã‚²ãƒ¼ãƒ æ“ä½œå°‚ç”¨ã®å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã«æˆ»ã™
    PlayerController->SetInputMode(inputMode); // å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’ã‚²ãƒ¼ãƒ ç”¨ã«è¨­å®š
    PlayerController->bShowMouseCursor = false; // ãƒã‚¦ã‚¹ã‚«ãƒ¼ã‚½ãƒ«ã‚’éè¡¨ç¤ºã«
}