// Fill out your copyright notice in the Description page of Project Settings.


#include "Setting.h"
#include "GameFramework/PlayerController.h"     // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©ãƒ¼é–¢é€£ã‚¯ãƒ©ã‚¹
#include "Kismet/GameplayStatics.h" // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼å–å¾—ã‚„ã‚µã‚¦ãƒ³ãƒ‰å†ç”Ÿãªã©ã®é™çš„ãƒ¦ãƒ¼ãƒ†ã‚£ãƒªãƒ†ã‚£
#include "GetUObjectClass.h"

// Sets default values
ASetting::ASetting()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

}

// Called when the game starts or when spawned
void ASetting::BeginPlay()
{
	Super::BeginPlay();
}

// Called every frame
void ASetting::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	if(bIsVisible)
	{
		APlayerController* playerController = UGameplayStatics::GetPlayerController(this, 0); // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©ãƒ¼å–å¾—
		if (settingWidgetClass)
		{
			UUserWidget* pauseWidget = CreateWidget<UUserWidget>(playerController, settingWidgetClass); // ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã®ä½œæˆ
		
			if (pauseWidget && pauseWidget->IsInViewport())  // ãƒ“ãƒ¥ãƒ¼ã«è¿½åŠ ã•ã‚Œã¦ã„ã‚‹æ™‚ã®ã¿
			{

				pauseWidget->RemoveFromParent();  // è¦ªã‹ã‚‰å‰Šé™¤
				pauseWidget->SetVisibility(ESlateVisibility::Collapsed); // å¼·åˆ¶çš„ã«éè¡¨ç¤ºã«è¨­å®š
				UE_LOG(LogTemp, Display, TEXT("ğŸ‘ğŸ‘ğŸ‘ğŸ‘"));
			
			}
		}
		bIsVisible = false;
	}

}

void ASetting::OnBackButtonClicked()
{
	UE_LOG(LogTemp, Display, TEXT("callğŸ‘"));
	bIsVisible = true;

}



